import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateCatalogSchema1789834302660 implements MigrationInterface {
    name = 'CreateCatalogSchema1789834302660'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "catalog"`);
        await queryRunner.query(`CREATE TYPE "catalog"."media_assets_asset_type_enum" AS ENUM('COVER', 'BANNER', 'THUMBNAIL', 'PROMOTION')`);
        await queryRunner.query(`CREATE TABLE "catalog"."media_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "asset_type" "catalog"."media_assets_asset_type_enum" NOT NULL, "storage_key" character varying(500) NOT NULL, "mime_type" character varying(50), "file_size" integer, "width" integer, "height" integer, "sort_order" integer NOT NULL DEFAULT '0', "alt_text" character varying(255), "series_id" uuid, "volume_id" uuid, "book_id" uuid, CONSTRAINT "PK_ca47e9f67a5e5d8af1e75d66ee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df9a0d81b5cf55ae1e76bcc9eb" ON "catalog"."media_assets"  ("series_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dee79355add18c7041459b1e21" ON "catalog"."media_assets"  ("volume_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_07a12ced4e9d7478b8ea817551" ON "catalog"."media_assets"  ("book_id") `);
        await queryRunner.query(`CREATE TYPE "catalog"."volumes_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "catalog"."volumes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "series_id" uuid NOT NULL, "volume_number" numeric(5,2) NOT NULL, "title" character varying(255), "slug" character varying(255) NOT NULL, "description" text, "sort_order" integer NOT NULL DEFAULT '0', "release_date" date, "status" "catalog"."volumes_status_enum" NOT NULL DEFAULT 'DRAFT', "published_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b1aeb61f030ce967e16d575c8a8" UNIQUE ("series_id", "volume_number"), CONSTRAINT "PK_f3d03a6ad79006b028d3eae9e9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_738661c5c68c6a83f9b375bcc0" ON "catalog"."volumes"  ("series_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1b7411f521c0a145b2100c129" ON "catalog"."volumes"  ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0abed5ea458b23418fa47ba42" ON "catalog"."volumes"  ("sort_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_06e5409d3711caf4e98aca40b3" ON "catalog"."volumes"  ("series_id", "sort_order") `);
        await queryRunner.query(`CREATE TYPE "catalog"."book_series_status_enum" AS ENUM('DRAFT', 'ONGOING', 'COMPLETED', 'HIATUS', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "catalog"."book_series" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "status" "catalog"."book_series_status_enum" NOT NULL DEFAULT 'DRAFT', "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_05bead859d346c10086ee2e1043" UNIQUE ("slug"), CONSTRAINT "PK_c6c5a77e8b605c605fadbcaec39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05bead859d346c10086ee2e104" ON "catalog"."book_series"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "catalog"."authors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "bio" text, "profile_image" character varying(500), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_f068a15d416578e89d41189ca25" UNIQUE ("slug"), CONSTRAINT "PK_d2ed02fabd9b52847ccb85e6b88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f068a15d416578e89d41189ca2" ON "catalog"."authors"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "catalog"."languages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "code" character varying(10) NOT NULL, CONSTRAINT "UQ_9c0e155475f0aa782e4a6178969" UNIQUE ("name"), CONSTRAINT "UQ_7397752718d1c9eb873722ec9b2" UNIQUE ("code"), CONSTRAINT "PK_b517f827ca496b29f4d549c631d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7397752718d1c9eb873722ec9b" ON "catalog"."languages"  ("code") `);
        await queryRunner.query(`CREATE TABLE "catalog"."categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_420d9f679d41281f282f5bc7d0" ON "catalog"."categories"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "catalog"."pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "chapter_id" uuid NOT NULL, "page_number" integer NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "storage_key" character varying(500) NOT NULL, "encrypted_key" character varying(500), "width" integer, "height" integer, "mime_type" character varying(50), "file_size" integer, "checksum" character varying(64), CONSTRAINT "UQ_c63f3da6bdfa01492b1b6b3ee2f" UNIQUE ("chapter_id", "page_number"), CONSTRAINT "PK_8f21ed625aa34c8391d636b7d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87a6e61d6c13a63ffd7b225b62" ON "catalog"."pages"  ("chapter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a11b53322cf9265d9c6e57853b" ON "catalog"."pages"  ("sort_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_e606ad6d4964c257fe4a9595b9" ON "catalog"."pages"  ("chapter_id", "sort_order") `);
        await queryRunner.query(`CREATE TYPE "catalog"."chapters_pricing_model_enum" AS ENUM('FREE', 'PARTIAL_FREE', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "catalog"."chapters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "book_id" uuid NOT NULL, "chapter_number" numeric(6,2) NOT NULL, "title" character varying(255), "sort_order" integer NOT NULL DEFAULT '0', "pricing_model" "catalog"."chapters_pricing_model_enum" NOT NULL DEFAULT 'FREE', "free_page_count" integer NOT NULL DEFAULT '0', "coin_cost" integer NOT NULL DEFAULT '0', "page_count" integer NOT NULL DEFAULT '0', "published" boolean NOT NULL DEFAULT false, "published_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a2bbdbb4bdc786fe0cb0fcfc4a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_23af8ea9e68fef63d07b189e8d" ON "catalog"."chapters"  ("book_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_af2c8752c093baa132a314b20c" ON "catalog"."chapters"  ("book_id", "chapter_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_65a153ca1870b096e2975deffe" ON "catalog"."chapters"  ("book_id", "sort_order") `);
        await queryRunner.query(`CREATE TABLE "catalog"."genres" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, CONSTRAINT "UQ_f105f8230a83b86a346427de94d" UNIQUE ("name"), CONSTRAINT "UQ_d1cbe4fe39bdfc77c76e94eada5" UNIQUE ("slug"), CONSTRAINT "PK_80ecd718f0f00dde5d77a9be842" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1cbe4fe39bdfc77c76e94eada" ON "catalog"."genres"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "catalog"."book_genres" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "book_id" uuid NOT NULL, "genre_id" uuid NOT NULL, CONSTRAINT "UQ_dc2d072b9d76acb4c5f2a4c55e6" UNIQUE ("book_id", "genre_id"), CONSTRAINT "PK_afd20a2f22d0efc47c5f80e14a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc378b8311ff85f0dd38f16309" ON "catalog"."book_genres"  ("book_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_43ff7d87d7506e768ca6491a1d" ON "catalog"."book_genres"  ("genre_id") `);
        await queryRunner.query(`CREATE TABLE "catalog"."tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "UQ_b3aa10c29ea4e61a830362bd25a" UNIQUE ("slug"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3aa10c29ea4e61a830362bd25" ON "catalog"."tags"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "catalog"."book_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "book_id" uuid NOT NULL, "tag_id" uuid NOT NULL, CONSTRAINT "UQ_671237e5d51f5f5c958337cd6a1" UNIQUE ("book_id", "tag_id"), CONSTRAINT "PK_8609713cdc27cfa8d6fa5cf80d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4d06db2d11048c09ca05de823d" ON "catalog"."book_tags"  ("book_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb495c7e106e0c1c6332797d68" ON "catalog"."book_tags"  ("tag_id") `);
        await queryRunner.query(`CREATE TYPE "catalog"."books_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "catalog"."books_pricing_model_enum" AS ENUM('FREE', 'PER_PAGE', 'PER_CHAPTER', 'PER_BOOK', 'SUBSCRIPTION')`);
        await queryRunner.query(`CREATE TABLE "catalog"."books" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "series_id" uuid NOT NULL, "volume_id" uuid, "title" character varying(255) NOT NULL, "japanese_title" character varying(255), "slug" character varying(255) NOT NULL, "description" text, "author_id" uuid, "artist_id" uuid, "language_id" uuid NOT NULL, "category_id" uuid NOT NULL, "status" "catalog"."books_status_enum" NOT NULL DEFAULT 'DRAFT', "pricing_model" "catalog"."books_pricing_model_enum" NOT NULL DEFAULT 'FREE', "default_coin_per_page" integer NOT NULL DEFAULT '0', "default_free_chapters" integer NOT NULL DEFAULT '0', "default_free_pages" integer NOT NULL DEFAULT '0', "is_premium" boolean NOT NULL DEFAULT false, "total_chapters" integer NOT NULL DEFAULT '0', "total_pages" integer NOT NULL DEFAULT '0', "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "total_views" bigint NOT NULL DEFAULT '0', "release_date" date, "published_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_4dc5a40933419641440fbd95e8e" UNIQUE ("slug"), CONSTRAINT "PK_f3f2f25a099d24e12545b70b022" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f020780ac748c90aba37a9a1bc" ON "catalog"."books"  ("series_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b072285eb40515cebcaf910689" ON "catalog"."books"  ("volume_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4dc5a40933419641440fbd95e8" ON "catalog"."books"  ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_1056dbee4616479f7d562c562d" ON "catalog"."books"  ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_843d886af4b43ed8ad753b658a" ON "catalog"."books"  ("artist_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3164a2958d73d8cdebe5204c83" ON "catalog"."books"  ("language_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_46f5b35b90175a660f99810bc9" ON "catalog"."books"  ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92606f78a31e625fe1ba164c81" ON "catalog"."books"  ("created_by") `);
        await queryRunner.query(`CREATE TABLE "catalog"."artists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "bio" text, "profile_image" character varying(500), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_d8698856b9f9735db7470841363" UNIQUE ("slug"), CONSTRAINT "PK_09b823d4607d2675dc4ffa82261" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8698856b9f9735db747084136" ON "catalog"."artists"  ("slug") `);
        await queryRunner.query(`ALTER TABLE "catalog"."media_assets" ADD CONSTRAINT "FK_df9a0d81b5cf55ae1e76bcc9eb0" FOREIGN KEY ("series_id") REFERENCES "catalog"."book_series"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."media_assets" ADD CONSTRAINT "FK_dee79355add18c7041459b1e218" FOREIGN KEY ("volume_id") REFERENCES "catalog"."volumes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."media_assets" ADD CONSTRAINT "FK_07a12ced4e9d7478b8ea817551a" FOREIGN KEY ("book_id") REFERENCES "catalog"."books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."volumes" ADD CONSTRAINT "FK_738661c5c68c6a83f9b375bcc0f" FOREIGN KEY ("series_id") REFERENCES "catalog"."book_series"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."pages" ADD CONSTRAINT "FK_87a6e61d6c13a63ffd7b225b627" FOREIGN KEY ("chapter_id") REFERENCES "catalog"."chapters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."chapters" ADD CONSTRAINT "FK_23af8ea9e68fef63d07b189e8d1" FOREIGN KEY ("book_id") REFERENCES "catalog"."books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_genres" ADD CONSTRAINT "FK_dc378b8311ff85f0dd38f163090" FOREIGN KEY ("book_id") REFERENCES "catalog"."books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_genres" ADD CONSTRAINT "FK_43ff7d87d7506e768ca6491a1dd" FOREIGN KEY ("genre_id") REFERENCES "catalog"."genres"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_tags" ADD CONSTRAINT "FK_4d06db2d11048c09ca05de823d6" FOREIGN KEY ("book_id") REFERENCES "catalog"."books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_tags" ADD CONSTRAINT "FK_fb495c7e106e0c1c6332797d684" FOREIGN KEY ("tag_id") REFERENCES "catalog"."tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" ADD CONSTRAINT "FK_f020780ac748c90aba37a9a1bce" FOREIGN KEY ("series_id") REFERENCES "catalog"."book_series"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" ADD CONSTRAINT "FK_b072285eb40515cebcaf9106892" FOREIGN KEY ("volume_id") REFERENCES "catalog"."volumes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" ADD CONSTRAINT "FK_1056dbee4616479f7d562c562df" FOREIGN KEY ("author_id") REFERENCES "catalog"."authors"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" ADD CONSTRAINT "FK_843d886af4b43ed8ad753b658a7" FOREIGN KEY ("artist_id") REFERENCES "catalog"."artists"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" ADD CONSTRAINT "FK_3164a2958d73d8cdebe5204c838" FOREIGN KEY ("language_id") REFERENCES "catalog"."languages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" ADD CONSTRAINT "FK_46f5b35b90175a660f99810bc97" FOREIGN KEY ("category_id") REFERENCES "catalog"."categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "catalog"."books" DROP CONSTRAINT "FK_46f5b35b90175a660f99810bc97"`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" DROP CONSTRAINT "FK_3164a2958d73d8cdebe5204c838"`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" DROP CONSTRAINT "FK_843d886af4b43ed8ad753b658a7"`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" DROP CONSTRAINT "FK_1056dbee4616479f7d562c562df"`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" DROP CONSTRAINT "FK_b072285eb40515cebcaf9106892"`);
        await queryRunner.query(`ALTER TABLE "catalog"."books" DROP CONSTRAINT "FK_f020780ac748c90aba37a9a1bce"`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_tags" DROP CONSTRAINT "FK_fb495c7e106e0c1c6332797d684"`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_tags" DROP CONSTRAINT "FK_4d06db2d11048c09ca05de823d6"`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_genres" DROP CONSTRAINT "FK_43ff7d87d7506e768ca6491a1dd"`);
        await queryRunner.query(`ALTER TABLE "catalog"."book_genres" DROP CONSTRAINT "FK_dc378b8311ff85f0dd38f163090"`);
        await queryRunner.query(`ALTER TABLE "catalog"."chapters" DROP CONSTRAINT "FK_23af8ea9e68fef63d07b189e8d1"`);
        await queryRunner.query(`ALTER TABLE "catalog"."pages" DROP CONSTRAINT "FK_87a6e61d6c13a63ffd7b225b627"`);
        await queryRunner.query(`ALTER TABLE "catalog"."volumes" DROP CONSTRAINT "FK_738661c5c68c6a83f9b375bcc0f"`);
        await queryRunner.query(`ALTER TABLE "catalog"."media_assets" DROP CONSTRAINT "FK_07a12ced4e9d7478b8ea817551a"`);
        await queryRunner.query(`ALTER TABLE "catalog"."media_assets" DROP CONSTRAINT "FK_dee79355add18c7041459b1e218"`);
        await queryRunner.query(`ALTER TABLE "catalog"."media_assets" DROP CONSTRAINT "FK_df9a0d81b5cf55ae1e76bcc9eb0"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_d8698856b9f9735db747084136"`);
        await queryRunner.query(`DROP TABLE "catalog"."artists"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_92606f78a31e625fe1ba164c81"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_46f5b35b90175a660f99810bc9"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_3164a2958d73d8cdebe5204c83"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_843d886af4b43ed8ad753b658a"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_1056dbee4616479f7d562c562d"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_4dc5a40933419641440fbd95e8"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_b072285eb40515cebcaf910689"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_f020780ac748c90aba37a9a1bc"`);
        await queryRunner.query(`DROP TABLE "catalog"."books"`);
        await queryRunner.query(`DROP TYPE "catalog"."books_pricing_model_enum"`);
        await queryRunner.query(`DROP TYPE "catalog"."books_status_enum"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_fb495c7e106e0c1c6332797d68"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_4d06db2d11048c09ca05de823d"`);
        await queryRunner.query(`DROP TABLE "catalog"."book_tags"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_b3aa10c29ea4e61a830362bd25"`);
        await queryRunner.query(`DROP TABLE "catalog"."tags"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_43ff7d87d7506e768ca6491a1d"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_dc378b8311ff85f0dd38f16309"`);
        await queryRunner.query(`DROP TABLE "catalog"."book_genres"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_d1cbe4fe39bdfc77c76e94eada"`);
        await queryRunner.query(`DROP TABLE "catalog"."genres"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_65a153ca1870b096e2975deffe"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_af2c8752c093baa132a314b20c"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_23af8ea9e68fef63d07b189e8d"`);
        await queryRunner.query(`DROP TABLE "catalog"."chapters"`);
        await queryRunner.query(`DROP TYPE "catalog"."chapters_pricing_model_enum"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_e606ad6d4964c257fe4a9595b9"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_a11b53322cf9265d9c6e57853b"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_87a6e61d6c13a63ffd7b225b62"`);
        await queryRunner.query(`DROP TABLE "catalog"."pages"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_420d9f679d41281f282f5bc7d0"`);
        await queryRunner.query(`DROP TABLE "catalog"."categories"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_7397752718d1c9eb873722ec9b"`);
        await queryRunner.query(`DROP TABLE "catalog"."languages"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_f068a15d416578e89d41189ca2"`);
        await queryRunner.query(`DROP TABLE "catalog"."authors"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_05bead859d346c10086ee2e104"`);
        await queryRunner.query(`DROP TABLE "catalog"."book_series"`);
        await queryRunner.query(`DROP TYPE "catalog"."book_series_status_enum"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_06e5409d3711caf4e98aca40b3"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_f0abed5ea458b23418fa47ba42"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_d1b7411f521c0a145b2100c129"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_738661c5c68c6a83f9b375bcc0"`);
        await queryRunner.query(`DROP TABLE "catalog"."volumes"`);
        await queryRunner.query(`DROP TYPE "catalog"."volumes_status_enum"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_07a12ced4e9d7478b8ea817551"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_dee79355add18c7041459b1e21"`);
        await queryRunner.query(`DROP INDEX "catalog"."IDX_df9a0d81b5cf55ae1e76bcc9eb"`);
        await queryRunner.query(`DROP TABLE "catalog"."media_assets"`);
        await queryRunner.query(`DROP TYPE "catalog"."media_assets_asset_type_enum"`);
        await queryRunner.query(`DROP SCHEMA IF EXISTS "catalog" CASCADE`);
    }

}
