export enum OtpPurpose {
    REGISTER = 'REGISTER',
    LOGIN = 'LOGIN',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
}

// UPCOMING FEILDS

// CHANGE_EMAIL
// CHANGE_PHONE
// DELETE_ACCOUNT
// PAYMENT
// WITHDRAW
// TWO_FACTOR